### ISSUE TITLE
Using with Business Fiber - VLAN2?

### ISSUE THREAD

**Issue by aggietallboy** [jaysoffian/eap_proxy#7]
Good Morning!

I've been troubleshooting why this isn't working with my Business Fiber and USG-4.

I *think* that it's running on VLAN 2 instead of 0

802.1Q Virtual LAN, PRI: 3, DEI: 0, ID: 2

I'm going to take a stab at it with the updated VLAN, and if that works, I'll take a stab at parameterizing it.

**Comment by aggietallboy** [comment]
no luck so far.. continuing to troubleshoot.

**Comment by aggietallboy** [comment]
Success!! 

We're connected using the VLAN 2 instead of VLAN 0.

**Comment by aggietallboy** [comment]
Three lines where the vlan is hard coded:

	Line 587:         if_vlan = args.if_wan + ".2"
	Line 597:         if_vlan = self.args.if_wan + ".2"
	Line 608:         if_vlan = args.if_wan + ".2"

I haven't done python programming, but as I said, I'll give it a shot at adding a new optional parameter --vlan=xx and filling the values here if present, or defaulting to .0 if not.

**Comment by aggietallboy** [comment]
OK.. first time working with python, so:

replace 
`if_vlan = args.if_wan + ".0"`

with:
`      if not args.--vlan:
			if_vlan = args.if_wan + ".0"
		else 
			if_vlan = args.if_wan + args.--vlan`

and then in parse_args()

```
g.add_argument(
		"--vlan", type=int, help=
        "Default runs as VLAN 0, override to another VLAN")

```

**Comment by aggietallboy** [comment]
ahh.. as i said.. first time wortking with python.. take the -- out

**Comment by bjsadler** [comment]
@aggietallboy I'm running into this issue now.  If I edit the eap_proxy.py file and just change those 3 lines to .2 instead of .0, I shouldn't have any issues?  I am having inconsistent connectivity when I just have the VIF interface set to VLAN 2, and CAN get a DHCP address assigned, but it's inconsistent and traffic flow is very hit or miss.  I'm using the default eap_proxy.py and my eap_proxy.sh script just has the copy MAC tag removed.
